---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: yes
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    docker_networks:
      - name: molecule
        ipam_config:
          - subnet: '10.0.0.0/24'
    networks:
      - name: molecule
        ipv4_address: '10.0.0.2'
  - name: nginx
    image: "nginx:1.18.0-alpine"
    command: ""
    docker_networks:
      - name: molecule
        ipam_config:
          - subnet: '10.0.0.0/24'
    networks:
      - name: molecule
        ipv4_address: '10.0.0.20'
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
...
